# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='exp',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='categorias',
            field=models.CharField(choices=[('0', 'Trabajos Practicos'), ('1', 'Ejemplo'), ('2', 'Otros')], default='0', max_length=6),
        ),
    ]
