# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160726_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='exp',
            field=models.CharField(max_length=60),
        ),
    ]
