# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160726_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulillo', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=b'')),
            ],
        ),
    ]
