# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_uploadfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='file',
            new_name='archivo',
        ),
    ]
