# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160726_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='archivo',
        ),
    ]
