# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='archivo',
            field=models.FileField(default='Suba una imagen', upload_to=b''),
            preserve_default=False,
        ),
    ]
