# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_post_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='archivo',
            field=models.FileField(default='', upload_to='static/imagenes'),
            preserve_default=False,
        ),
    ]
