# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20160726_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='archivo',
            field=models.ImageField(default='blog/imagenesubidas/noimg.png', upload_to='blog/imagenesubidas/'),
        ),
    ]
