# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20160726_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='archivo',
            new_name='imagen',
        ),
    ]
