# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20160726_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nombimg',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
