# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_post_nombimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nombimg',
            new_name='nombre_imagen',
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='blog/static/css/imagenes/pelota.png', upload_to='blog/static/subidas/img'),
        ),
    ]
