# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20160727_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nombre_imagen',
            field=models.CharField(max_length=80),
        ),
    ]
