# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_remove_post_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imagen',
        ),
        migrations.AddField(
            model_name='post',
            name='exp',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
