# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20160727_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='blog/static/css/imagenes/pelota.png', upload_to='blog/static/subidas/img'),
        ),
    ]
