# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_post_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nombre_imagen',
        ),
    ]
