# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_remove_post_nombre_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nombre_imagen',
            field=models.CharField(default='.png', max_length=80),
            preserve_default=False,
        ),
    ]
