# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_auto_20160729_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='blog/static/css/imagenes/pelota.png', upload_to='blog/static/subidas/img'),
        ),
    ]
